version: '3.8'

services:
  intern-postgres:
    container_name: intern-postgres
    image: postgres:11
    environment:
      POSTGRES_DB: intern-starter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NPhTQts4pwfdasjs
    ports:
      - "5432:5432"
    networks:
      - es-network

  basicstarter-server:
    container_name: basicstarter-server
    image: eztekdocker.azurecr.io/basicstarter-staging:latest
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    ports:
      - "8080:8080"
    depends_on:
      - intern-postgres
    links:
      - intern-postgres
    networks:
      - es-network

networks:
  es-network:
    driver: bridge
